### ISSUE TITLE
Issue when importing pyrho

### ISSUE THREAD

**Issue by d-massa** [materialsproject/pyrho#106]
Hi, 

I would like to report an issue I encounter when I try to import pyrho in my jupyter notebook, running with Python 3.9.12, installed with pip3 install pyrho

`import pyrho as phr` is enough to reproduce the issue, which leads to a TypeError which I copy here down below. 

Thank you

TypeError                                 Traceback (most recent call last)
/home/massad/gitloc/EDNet/BuildingMPDataset.ipynb Cell 13 in <cell line: 2>()
      [1](vscode-notebook-cell:/home/massad/gitloc/EDNet/BuildingMPDataset.ipynb#X15sZmlsZQ%3D%3D?line=0) import numpy as np
----> [2](vscode-notebook-cell:/home/massad/gitloc/EDNet/BuildingMPDataset.ipynb#X15sZmlsZQ%3D%3D?line=1) import pyrho as phr

File ~/anaconda3/lib/python3.9/site-packages/pyrho/__init__.py:37, in <module>
     34 import numpy as np
     36 # Place all submodule functions and variables into namespace
---> 37 from pyrho.parameters import *
     38 from pyrho.utilities import *
     39 from pyrho.loadData import * #import loadData

File ~/anaconda3/lib/python3.9/site-packages/pyrho/parameters.py:534, in <module>
    529 #squarePulses = ['custom', 'delta', 'step', 'rectifier', 'shortPulse', 'recovery'] #{'custom': True, 'delta': True, 'step': True, 'rectifier': True, 'shortPulse': True, 'recovery': True}
    530 #arbitraryPulses = ['custom', 'sinusoid', 'chirp', 'ramp'] #{'custom': True, 'sinusoid': True, 'chirp': True, 'ramp':True} # Move custom here
    532 smallSignalAnalysis = ['delta', 'step', 'sinusoid'] 
--> 534 protParams['custom'].add_many(('phis',  [1e16,1e17],        0,      None,   mole*mm**-2*second**-1, '\mathbf{\phi}', 'List of flux values'), #'photons/s/mm^2'
    535                             ('Vs',      [-70,-20,10],       None,   None,   mV, '\mathbf{\mathrm{V}}', 'List of voltage clamp values (if applied)'), #'mV'
    536                             ('delD',    25,                 0,      1e9,    ms, '\Delta t_{delay}', 'Delay duration before the first pulse'), #'ms'
    537                             ('cycles',  [[150.,50.]],       0,      None,   ms, 'cycles',           'List of [on, off] durations for each pulse'))#, #'ms'#,
    539 protParams['step'].add_many(('phis',    [1e16,1e17],        0,      None,   mole*mm**-2*second**-1, '\mathbf{\phi}', 'List of flux values'), #'photons/s/mm^2'
    540                             ('Vs',      [-70,-40,-10,10,40,70], None,   None,   mV, '\mathbf{\mathrm{V}}', 'List of voltage clamp values (if applied)'), #'mV'
    541                             ('delD',    25,                 0,      1e9,    ms, '\Delta t_{delay}', 'Delay duration before the first pulse'), #'ms'
    542                             ('cycles',  [[150.,100.]],      0,      None,   ms, 'cycles',           'List of [on, off] durations for each pulse')) #'ms'
...
    236     raise ValueError("'%s' is not a Parameter" % par)
--> 237 OrderedDict.__setitem__(self, key, par)
    238 par.name = key

TypeError: descriptor '__setitem__' requires a 'collections.OrderedDict' object but received a 'PyRhOparameters'

**Comment by jmmshn** [comment]
Hi @d-massa, please make sure you are installing from here:
https://pypi.org/project/mp-pyrho/
or from the present GitHub repo.
I will update the documentation.
